PENDING = 'pending'
PENDING_SETTLEMENT = 'pending_settlement'
FAILED = 'failed'
CANCELED = 'canceled'
COMPLETE = 'complete'
ERROR = 'error'
AVS_DESCRIPTIONS = dict(
	A='Street address matches, but 5-digit and 9-digit postal code do not match.',
	B='Street address matches, but postal code not verified.',
	C='Street address and postal code do not match.',
	D='Street address and postal code match. Code "M" is equivalent.',
	E='AVS data is invalid or AVS is not allowed for this card type.',
	F='Card member\'s name does not match, but billing postal code matches.',
	G='Non-U.S. issuing bank does not support AVS.',
	H='Card member\'s name does not match. Street address and postal code match.',
	I='Address not verified.',
	J='Card member\'s name, billing address, and postal code match.',
	K='Card member\'s name matches but billing address and billing postal code do not match.',
	L='Card member\'s name and billing postal code match, but billing address does not match.',
	M='Street address and postal code match. Code "D" is equivalent.',
	N='Street address and postal code do not match.',
	O='Card member\'s name and billing address match, but billing postal code does not match.',
	P='Postal code matches, but street address not verified.',
	Q='Card member\'s name, billing address, and postal code match.',
	R='System unavailable.',
	S='Bank does not support AVS.',
	T='Card member\'s name does not match, but street address matches.',
	U='Address information unavailable. Returned if the U.S. bank does not support non-U.S. AVS or if the AVS in a U.S. bank is not functioning properly.',
	V='Card member\'s name, billing address, and billing postal code match.',
	W='Street address does not match, but 9-digit postal code matches.',
	X='Street address and 9-digit postal code match.',
	Y='Street address and 5-digit postal code match.',
	Z='Street address does not match, but 5-digit postal code matches.',
)
AVS_DOMESTIC_CODES = ('A', 'E', 'N', 'R', 'S', 'U', 'W', 'X', 'Y', 'Z')
AVS_INTERNATIONAL_CODES = ('B', 'C', 'D', 'G', 'I', 'M', 'P')
AVS_AMEX_CODES = ('F', 'H', 'J', 'K', 'L', 'O', 'Q', 'T', 'V')
